# cloudbuild.yaml

steps:
  # Step 1: Build the Docker image using your Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}',
      '.'
    ]
    id: 'Build Docker Image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}']
    id: 'Push to Artifact Registry'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      '${_SERVICE_NAME}',
      '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}',
      '--region=${_REGION}',
      '--platform=managed',
      '--allow-unauthenticated',
      '--port=3000',
      '--set-secrets=VAPI_API_KEY=vapi-api-key:latest',
      '--memory=512Mi',
      '--timeout=300s'
    ]
    id: 'Deploy to Cloud Run'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

substitutions:
  _REGION: 'us-central1'
  _AR_REPO_NAME: 'nextjs-apps'
  _IMAGE_NAME: 'rotating-orb'
  _SERVICE_NAME: 'rotating-orb'

# logsBucket: 'gs://vapi-orb_cloudbuild' # << REMOVED OR COMMENTED OUT
# serviceAccount: 'cloud-build-sa@vapi-orb.iam.gserviceaccount.com' # << REMOVED OR COMMENTED OUT