# cloudbuild.yaml

steps:
  # ... (build step) ...
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}', # Uses _AR_REPO_NAME
      '.'
    ]
    id: 'Build Docker Image'

  # ... (push step) ...
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'] # Uses _AR_REPO_NAME
    id: 'Push to Artifact Registry'

  # ... (deploy step) ...
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      '${_SERVICE_NAME}',
      '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}', # Uses _AR_REPO_NAME
      # ... other deploy args ...
    ]
    id: 'Deploy to Cloud Run'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}' # Uses _AR_REPO_NAME

substitutions:
  _REGION: 'us-central1'
  _AR_REPO_NAME: 'nextjs-orb-repo'
  _IMAGE_NAME: 'rotating-orb'
  _SERVICE_NAME: 'rotating-orb'

options:
  logging: CLOUD_LOGGING_ONLY